### ISSUE TITLE
Random generation in Haskell

### ISSUE THREAD

**Issue by Sergey-A-Dovgal** [maciej-bendkowski/boltzmann-brain#9]
Instead of linear (on the number of states) generation I think we need to implement logarithmic generation either by hand or by using some builtin library. For example, in Python such tool exists. It is a bit cumbersome to construct the Knuth-Yao tree by hand, I ope that you will find something.

**Comment by maciej-bendkowski** [comment]
Please be more specific about the nature of the the enhancement you think should be implemented. I assume you mean "logarithmic" as in choosing the correct branch (i.e. constructor) of a constructed type not in linear time, but rather in logarithmic time using some sort of additional tree structure. If so, please update the issue title accordingly, so that it reflects the true nature of the issue.

I think it's a rather low priority issue (assuming the above mentioned nature of the problem) at the current moment. Nonetheless, for huge transfer matrix samplers this might have a theoretical impact on the effectiveness of the sampler, though it's not clear that it might manifest in practice. We should keep an eye on this once we have efficient samplers for huge transfer matrix specifications.

**Comment by maciej-bendkowski** [comment]
Commit ca7d5c8365e419fc910c6849773a9de024d7ef61 provides an experimental support for discrete decision trees in the spirit of Knuth and Yao, using an external library buffon-machines. Given a set of probabilities corresponding to some random choice, it's possible to _hardcode_ a suitable decision tree meant to require as few random bits as possible. So, for instance, instead of drawing a random real in the interval (0,1) one can draw successive bits and traverse the tree accordingly.  Such an approach allows us to save random bits as, on average, we consume a lot less than 32 bits per choice. Interestingly, even though the constructed decision trees are not optimal in the sense of Knuth and Yao, they lead to a notable speedup in the sampling process. Both theoretical calculations and empirical experimentation suggests that sampling can be faster a few times, even as fast as 12 times on some specifications (sic!).

In order to get even more efficient, the decision tree is calculated at _compile time_ using TemplateHaskell. Hence, once the module is compiled, there's no overhead in computing the respective decision trees.

Similar changes can (and will) be implemented for rational specifications soon.

**Comment by maciej-bendkowski** [comment]
Commit d81f679731e39e5535e20d332bf23d622280706e alters the rational sampler so that it uses Buffon machines, like the algebraic sampler. This should close the current feature request.
